version: 2
jobs:
  build:
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    working_directory: ~/noms-digital-studio/licences-feature-specs
    steps:
      - checkout
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: feature tests for mock
          command: ./gradlew clean mockTest
      - store_test_results:
          path: ./build/test-results
          destination: junit
      - store_artifacts:
          path: ./build/geb-reports
          destination: mock/geb
      - store_artifacts:
          path: ./build/test-results
          destination: mock/test-results
  accept_stage:
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    working_directory: ~/noms-digital-studio/licences-feature-specs
    steps:
      - checkout
      - restore_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          key: gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: feature tests for mock
          command: ./gradlew clean stageTest
      - store_test_results:
          path: ./build/test-results
          destination: junit
      - store_artifacts:
          path: ./build/geb-reports
          destination: stage/geb
      - store_artifacts:
          path: ./build/test-results
          destination: stage/test-results
workflows:
  version: 2
  acceptance:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
